### ISSUE TITLE
Show medication history in a calendar view

### ISSUE THREAD

**Issue by estux** [Futsch1/medTimer#137]
Hello, I started using the app to track and remember pills for a time-constrained treatment (only 15-20 days of pills), e.g. flu/sore throat related.
Now I should stop taking them and come back to take my regular supplements (like Vitamin D or other vitamins/minerals) but it seems the app doesn't consider time constrained treatments. 
- How can I stop reminders for the pills I don't have to take anymore? (I haven't found a Delete button in the reminders screen of every medicine) Should I remove the medicine completely? 
- I would like to keep notes about taken medicine, if I remove them from the list do they disappear also from the history?

---

- Related to this....I think there should be an easier way to navigate history apart from Tabular View (maybe it's better to open another issue for this)

Thank you very much for your work! The app is really useful 💯 🤩

**Comment by Futsch1** [comment]
Hey estux, thanks a lot for your feedback.

You can delete reminders or medicines by swiping them to the left. So you can delete all reminders for a medicine if you want to keep it or maybe take it again at a later time.

The history will stay as it is no matter what you do with the medicines (renaming, changing colors, deleting etc.).

I am considering adding a calendar view where you can select days and see the medicine taken on that day - would that help or would you think this is an easier way of navigating instead of the tabular view?

**Comment by estux** [comment]
Thanks for your fast reply!
I honestly didn't know I could delete reminders swiping left. Maybe adding some visual indications you could act with gestures or a first start guide could help with this.
Yes, calendar view (maybe together with list view ordered by day, like calendars app) could help a lot!
Thank you again, your app is great and was really needed in the open source world!

**Comment by Futsch1** [comment]
The calendar view should not only include past reminder events, but also show the future one (especially useful for cyclic reminders).
