### ISSUE TITLE
MQTT integration for automations

### ISSUE THREAD

**Issue by jceloria** [Futsch1/medTimer#153]
As the title suggests, being able to publish to a message queue when reminders go off would be a nice to have. Automation systems could then do things like trigger lights flashing, TTS, play mp3's, etc. Integration into systems like Home Assistant, Hubitat, OpenHAB, etc could allow people to create their own notifications.

**Comment by pataquets** [comment]
Maybe some generic Tasker integration would cover more methods to broadcast notifications and alarms.

**Comment by Futsch1** [comment]
That is indeed a nice suggestion.

I just tried it: You can setup a tasker profile that triggers on a new notification by MedTimer. With this, you can start an arbitrary task interacting with other apps or your home automation.

As an alternative, I have found this thread: https://www.reddit.com/r/tasker/comments/bkw3nd/how_can_i_forward_a_push_notification_from_a/ (might be no longer relevant).

Since it would be necessary to add internet permissions to the app statically, thus breaking the main privacy concept, I will not implement the feature in MedTimer and ask you to rely on third party solutions like [Tasker](https://tasker.joaoapps.com/).

**Comment by pataquets** [comment]
Oh, that's just awesome! Thanks for figuring it out and posting back, @Futsch1.
I think this is worth sharing in the documentation, since it's both a feature and a usage information. 
And, sharing your concern about privacy, being able to achieve it without requiring further permissions only adds to the already great feature list.

**Comment by jceloria** [comment]
Tasked is fine, but unfortunately the mqtt plugins are unreliable. I'll have to find another solution, thank you for the consideration anyway.

**Comment by pataquets** [comment]
If http works for you, you might be interested in this:
https://play.google.com/store/apps/details?id=ch.rmy.android.http_shortcuts

Not tried with Tasker, thou.
