### ISSUE TITLE
Feature request: deactivate all reminders of a medication

### ISSUE THREAD

**Issue by a10n-jsd** [Futsch1/medTimer#227]
Thank you so much for making this great app. I use it mainly for my children's medication.

I think pause or stop medication is a must have feature for a medication app. Imagine if you take OTC medicine, let say ibuprofen, and your illness still occur, so you meet the doctor. The doctor prescribes a prescription drug, ergotamine, and tells you to stop taking ibuprofen.

I think it's good to add more action here, between "edit" and "delete":

![pause/stop](https://i.imgur.com/d2ok4KH.png)

All the best to you.

**Comment by Futsch1** [comment]
Thank you for your feedback and feature request. I recently added #216, which would make it possible to deactivate  reminders of a medicine. This would solve your use case, but might be cumbersome if you have a medicine with more than one reminder.

That's why I will add an option to activate and deactivate all reminders of a medicine using the kebab menu icon (top right).
