### ISSUE TITLE
reminders at fix interval from last taken dose

### ISSUE THREAD

**Issue by mosiser** [Futsch1/medTimer#362]
I really like the "linked/following" feature.
What I would find very useful (and I have searched in vain in other apps), it's a way to move the next reminders to a fixed interval from the last taken dose.

Example:
- I take a pill every 7 days (Mondays)
- one day I skip the dose and take the pill the next day (Tuesday)
- from now on, the reminders should move to Tuesdays

Same with months:
 15/04, 15/05, 15/06 -> 18/06, 18/07, 18/08 -> 22/08, 22/09, etc... (not necessary the same day of the month, it could be "every 30 days"...)

Is it feasible, or too hard to implement?
Every time my parents skip a dose, I have to manually redo all the schedule...

Thanks

**Comment by Futsch1** [comment]
This would for sure be feasible, I do not even consider it very complex from the implementation standpoint. What might be more challenging is the UI side of it.

I would propose to be able to create two types of reminders on the medicine view: Time-based reminder (current reminders) and Interval-based reminders (new feature).

For interval based reminders I would have to set a starting point (date and time) and then select an interval in an arbitrary time unit (anything between minutes and months - or days, since months might have some issues given their different length). It would also be possible to select if the next reminder should be scheduled based on the reminded time (=fixed time intervals) or on the taken time (= fixed time between taken events, similar to the following reminders we have now).

Now coming back to your feature request: Would the schedule based on taken time already satisfy your request? Or would you want something like: I take the pill Mondays at 8 pm. So if I miss it one day and take it on Tuesday at 8:30 pm, it should remind the next time on Tuesday 8 pm (and not at 8:30 pm, as the schedule based on taken time would suggest).

**Comment by mosiser** [comment]
It would be perfect.
Thank you very much.

> Now coming back to your feature request: Would the schedule based on taken time already satisfy your request? Or would you want something like: I take the pill Mondays at 8 pm. So if I miss it one day and take it on Tuesday at 8:30 pm, it should remind the next time on Tuesday 8 pm (and not at 8:30 pm, as the schedule based on taken time would suggest).

Probably, the best and preferable solution would be to use the original scheduled time, but I understand this would be a further complication. The simpler way is still a good solution.

---
If I can leave some ideas, maybe the interval should be triggered not only by a taken dose, but also by a skipped dose. 
Thinking about it:
Monday-1 (taken), Monday-2 (snoozed) -> Tuesday-2 (taken), Tuesday-3 (snoozed) -> Wedsnday-3 (skipped)... next?
Best would be Tuesday-4 (last taken one), but is probably harder to implement. So the easier would be Wedsnday-4...

And, still connected to this function, I have seen your #147 proposal and its unfeasibility: thinking of people that snooze their dose to the next day, maybe a fixed "snooze to tomorrow" button in the notification would be doable?

Just some thoughts, I don't want to bother you... 😅
