### ISSUE TITLE
Include UTC datetime in export

### ISSUE THREAD

**Issue by ajsteele** [Futsch1/medTimer#405]
**Is your feature request related to a problem? Please describe.**
When exporting as CSV, the timestamps seem to be in local time. I've only tried this in one time zone so far, but I assume this will cause issues when travelling.

**Describe the solution you'd like**
Include a column with UTC datetime values for when medication was taken, in addition to local time. Ideally, local time should be formatted to include time zone offset too. [This page](https://documentation.sas.com/doc/en/vdmmlcdc/8.1/leforinforref/p1a0qt18rxydrkn1b0rtdfh2t8zs.htm) seems to give some guidance on how to do this in an ISO-compliant way. :)

Thanks!

**Comment by Futsch1** [comment]
Timestamps are indeed in local time. I see no issue in adding another column with the ISO timestamp.

However, since the most common use case would be to continue editing the CSV with Excel, using ISO 8601 timestamps everywhere including time zone offsets is not a good idea: Excel cannot parse those per default. So I would include two columns for the reminded and taken timestamps in ISO 8601 time format, but in the local timezone (there, the UTC+0 offset is part of the format and can be used to calculate the UTC+0 timestamp, offering flexibility for further conversion tasks).

**Comment by ajsteele** [comment]
Makes sense, thanks! I usually process in R or Python but perhaps I’m not the typical user… I guess you could make the export columns customisable, but that might be overkill. :)
