### ISSUE TITLE
feature req: support older versions of Android.

### ISSUE THREAD

**Issue by nutpantz** [Futsch1/medTimer#41]
While it is always great to have the newest stuff most people especially the elderly have older devices(for example Amazon only uses Android 11 on the newest hardware (fire tablet hd 10 or 11 2023)
Many people are unable to buy the latest hardware and in north America almost everything is locked from community updates.

It would be great if you could support older hardware like Android 9+

**Comment by Futsch1** [comment]
I totally understand that support for older devices would be desirable for this app.

I started this project with the intention to make use of the newest set of Android features and consequently used these to quite some extent. I checked, but reducing the minSDK version would require major re-work and re-testing of some aspects of the app.

So I am very sorry to decline your request, since I'd like to focus rather on adding features and streamlining the app.
