### ISSUE TITLE
Panic!!!!  30.000 notifications this morning!!!

### ISSUE THREAD

**Issue by Django-BOfH** [Futsch1/medTimer#58]
I received almost 30,000 notifications for my 4 medications this morning. So either there's a buffer overflow or the app has been knocked out by the summer time changeover!
I'd have to delete all notifications, as otherwise notifications were constantly coming in!

**Comment by Futsch1** [comment]
duplicates #57 

I already fixed it this morning in v1.5.1 since the same happened to me (Google rollout might take a couple of days and tomorrow it will be fine again even with the older version)... I am very sorry for this issue and the inconvenience, but seemingly I'm not the only one that gets DST done wrong, there's even a scientific paper on it: https://ieeexplore.ieee.org/document/8816815
