### ISSUE TITLE
Restore events

### ISSUE THREAD

**Issue by Django-BOfH** [Futsch1/medTimer#62]
OK, it may well be that I'm getting a bit old and don't realise things so quickly. ;) Saving and restoring the medication schedule now works. Exporting the events is quite simple. But how and where can I restore previously saved events in the app, i.e. restore the events?

**Comment by Futsch1** [comment]
This is not implemented yet, so it is indeed hard to find ;-)

I wouldn't consider this a high prio feature since events can already be exported and you usually wouldn't need them imported back into the app as a part of the backup from my opinion. But maybe I'm overlooking some use case?

So I'll keep it open and as To-Do, but not very high prio as mentioned.

**Comment by Django-BOfH** [comment]
OK, that of course explains why the option cannot be found.

After the app could not be updated via the Google App Store or F-Droid, I had to delete the app and reinstall it. The history of the last month was then also lost. :/ Hence my endeavour to restore the event history ...
